# Generated by Django 4.2.19 on 2025-03-25 12:33

from django.db import migrations, models
import solar_panel_web_page.main_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100, validators=[solar_panel_web_page.main_app.validators.IsItAPhoneNumber()])),
                ('consultation_datetime', models.DateTimeField(validators=[solar_panel_web_page.main_app.validators.DateChecker()])),
                ('description', models.TextField()),
            ],
        ),
    ]
