# Generated by Django 4.2.19 on 2025-04-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL на изображението')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване')),
            ],
        ),
    ]
