# Generated by Django 4.2.19 on 2025-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secondary_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Допълнително изображение'),
        ),
    ]
