# Generated by Django 4.2.19 on 2025-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_project_secondary_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Път към поста в социалните мрежи'),
        ),
    ]
